# Generated by Django 4.2.18 on 2025-02-03 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HATApp', '0004_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='message',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='message',
            name='encryption_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='processed_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
